// Code generated by "stringer -linecomment -type Element element.go"; DO NOT EDIT.

package design

import "strconv"

const _Element_name = "UndefinedrectUndefined"

var _Element_index = [...]uint8{0, 9, 13, 22}

func (i Element) String() string {
	if i < 0 || i >= Element(len(_Element_index)-1) {
		return "Element(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Element_name[_Element_index[i]:_Element_index[i+1]]
}
