package design

import (
	"fmt"
	"os"
	"testing"
)

func Test_save_all_shapes(t *testing.T) {
	cases := []struct {
		width, height, x, y int
		shape               Shape
		filename            string
	}{
		{300, 150, 0, 0, NewRecord(Record{}).WithFields(), "shapes/record.svg"},
		{200, 100, 50, 50, NewCircle("Circle"), "shapes/circle.svg"},
	}
	shapes, err := os.Create("shapes.md")
	if err != nil {
		t.Fatal(err)
	}
	shapes.WriteString("# Shapes\n\nGenerated by shape_test.go\n\n")
	defer shapes.Close()
	for _, c := range cases {
		graph := NewGraph()
		graph.Width = c.width
		graph.Height = c.height
		fh, err := os.Create(c.filename)
		if err != nil {
			t.Error(err)
		}
		graph.Place(c.shape).At(c.x, c.y)
		graph.WriteTo(fh)
		format := "<img src=%q />\n<br clear=\"all\">"
		shapes.WriteString(fmt.Sprintf(format, c.filename))
		fh.Close()
		t.Logf("Saved %s", c.filename)
	}
}
