package design

import (
	"fmt"
	"os"
	"testing"
)

func Test_save_all_shapes(t *testing.T) {
	cases := []struct {
		shape    Shape
		filename string
	}{
		{NewRecord(Record{}).WithFields(), "shapes/record.svg"},
	}
	shapes, err := os.Create("shapes.md")
	if err != nil {
		t.Fatal(err)
	}
	shapes.WriteString("# Shapes\n\nGenerated by shape_test.go\n\n")
	defer shapes.Close()
	for _, c := range cases {
		graph := NewGraph()
		fh, err := os.Create(c.filename)
		if err != nil {
			t.Error(err)
		}
		graph.Place(c.shape).At(10, 10)
		graph.WriteTo(fh)
		shapes.WriteString(fmt.Sprintf("<img src=%q />\n", c.filename))
		fh.Close()
		t.Logf("Saved %s", c.filename)
	}
}
